# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59d02646582ac45d45d7f633c77705a0b74bbe7e3fca70ae1f3f50b44fe03962aea9d6e9b8cb7b926718283fae756ac3290e3a474cbe7e80e54a5fb1c5f4be55

test:
  secret_key_base: c2c8ee692cb8dbb9a692aa278d6b18720fcd0531305d916363ce49978c12fa61bef2b08d3b2ec817844aeb98b59c68e27b8a4b8c9c48f170b51717c70424f1e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
